version = 0.1

[default.deploy.parameters]
stack_name = "lab03-classifier-v2"
resolve_s3 = true
s3_prefix = "lab03-classifier-v2"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
